FORMAT: 1A
HOST: http://localhost:21092/

# Restaurant API

API Rest para ações de cadastro, edição e exclusão de restaurantes e seus produtos.

## Restaurantes [/public/restaurant/]

### Cadastrar restaurante [POST]

+ Attributes
    - url_image_restaurant (string) - Imagem do restaurante
    - restaurant_name (string, required)- Nome do restaurante
    - street (string, required) - Rua do restaurante
    - neighborhood (string, required) - Bairro do restaurante
    - city (string, required) - Cidade do restaurante
    - number (string, required) - Número do endereço do restaurante
    - zipcode (string, required) - CEP do restaurante

+ Request (application/json)

        {
            "url_image_restaurant": "imagem-do-restaurante.png"
            "restaurant_name": "Nome do restaurante",
            "street": "Rua XYZ",
            "neighborhood": "Bairro",
            "city": "Cidade",
            "number": "Número do endereço",
            "zipcode": "Cep do endereço"
        }

+ Response 200 (application/json)

    + Body

            {
               success: true
            }


+ Response 400 (application/json)

       {
            "message": "Não foi possível cadastrar o restaurante pois há erros no preenchimento dos campos",
            "details":
                [
                    {
                        "field": "Campo com erro",
                        "message": "Motivo do erro"
                    }
                ]
        }

### Listar todos restaurantes [GET]
    Consulta de todos os restaurantes cadastrados

+ Response 200 (application/json)

        [
            {
                "id_restaurant": 1,
                "url_image_restaurant": "",
                "restaurant_name": "Nome restaurante",
                "street": "Rua XYZ",
                "neighborhood": "Centro",
                "number": "1000",
                "zipcode": "98787000",
                "city": "Cidade"
            },
            {
                "id_restaurant": 2,
                "url_image_restaurant": "",
                "restaurant_name": "Nome restaurante 2",
                "street": "Rua XYZ",
                "neighborhood": "Centro",
                "number": "1000",
                "zipcode": "98787000",
                "city": "Cidade"
            }
        ]
        
+ Response 400 (application/json)

        {
             "error": "Motivo do erro"
        }

### Listar restaurante por ID [GET /public/restaurant/:id]
    Consulte um restaurante específico passando o seu id
    
+ Response 200 (application/json)

        {
            "id_restaurant": 1,
            "url_image_restaurant": "",
            "restaurant_name": "Nome restaurante",
            "street": "Rua XYZ",
            "neighborhood": "Centro",
            "number": "1000",
            "zipcode": "98787000",
            "city": "Cidade"
        },
    
+ Response 400

        {
            "error": "Motivo do erro"
        }
    
### Alterar dados do restaurante [PUT /public/restaurant/{id}]

+ Request (application/json)

        {
            "url_image_restaurant": "imagem-do-restaurante.png",
            "restaurant_name": "Nome do restaurante",
            "street": "Rua XYZ",
            "neighborhood": "Bairro",
            "city": "Cidade",
            "number": "Número do endereço",
            "zipcode": "Cep do endereço"
        }

+ Response 200 (application/json)

    + Body

            {
               success: true
            }
        
### Excluir restaurante [DELETE /public/restaurant/{id}]

+ Response 200 (application/json)

    + Body

            {
               success: true
            }
        
## Pratos [/public/products/]


### Cadastrar pratos [POST]

+ Attributes
    - url_image_product (string) - Imagem do prato
    - id_restaurant (string, required) - ID do restaurante do prato
    - product_name (string, required)- Nome do prato
    - description (string, required) - Descrição do prato
    - price (number, required) - Valor do prato
    - category (string, required) - Categoria do prato
    - promotion (boolean, required) - Indica quais pratos estão em promoção
    - description_promotion (string) - Descrição da promoção (obrigatório somente se prato em promoção)
    - start_promotion (string) - Data de inicio da promoção (obrigatório somente se prato em promoção)
    - end_promotion (string) - Data final da promoção (obrigatório somente se prato em promoção)
    - price_promotion (number) - Valor do produto durante a promoção (obrigatório somente se prato em promoção)

+ Request (application/json)

        {
            "url_image_product": "imagem-do-prato.png",
            "id_restaurant": 1,
            "product_name": "Nome do prato",
            "description": "Descrição",
            "price": 25.90,
            "category": "Massas",
            "promotion": false,
            "description_promotion": "Black November da loja XYZ",
            "start_promotion": "2023-11-01",
            "end_promotion": "2023-11-30",
            "price_promotion": 15.00
        },

+ Response 200 (application/json)

    + Body

            {
               success: true
            }


+ Response 400 (application/json)

   {
        "message": "Não foi possível cadastrar o produto pois há erros no preenchimento dos campos",
        "details":
        [
            {
                "field": "Campo com erro",
                "message": "Motivo do erro"
            }
        ]
    }

### Listar todos os pratos cadastrados [GET /public/product/{id_restaurant}]
    Consulta de todos os pratos de um restaurante cadastrado

+ Response 200 (application/json)

        [
                {
                    "id_product": 2,
                    "id_restaurant": 1,
                    "url_image_product": null,
                    "product_name": "Macarronada",
                    "description": "Tomate italiano e orégano",
                    "price": 25,
                    "category": "Massas",
                    "promotion": false
                },
                {
                    "id_product": 2,
                    "id_restaurant": 1,
                    "url_image_product": null,
                    "product_name": "Risoto de alho poró",
                    "description": "Arroz premium, alho poró",
                    "price": 95,
                    "category": "Risotos",
                    "promotion": true,
                    "description_promotion": "Black November",
                    "price_promotion": 75,
                    "start_promotion": "31/10/2023",
                    "end_promotion": "29/11/2023"
                }
        ]
+ Response 400 (application/json)

        {
        "error": "Motivo do erro"
        }
        
### Alterar dados de um prato [PUT /public/restaurant/{idproduct}]

+ Parameters

    + idproduct - ID do produto

+ Response 200 (application/json)

    + Body

            {
               success: true
            }
            
+ Response 400 (application/json)

        {
            "error": "Motivo do erro"
        }
        
### Excluir prato [DELETE /public/restaurant/{idproduct}/restaurant/{idRestaurant}]

+ Parameters

    + idproduct - ID do produto
    + idRestaurant - ID do restaurante em que o prato está cadastrado

+ Response 200 (application/json)

    + Body

            {
               success: true
            }
            
+ Response 400 (application/json)

        {
            "error": "Motivo do erro"
        }